name: Guillaume Querin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59594
title: Web CV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003980'
    - '#2163ad'
    - '#3179c3'
    - '#4896e1'
    - '#5caffd'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
