name: Guillaume Querin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#335384'
    - '#010101'
    - '#92b2e1'
    - '#607382'
  brandStrength: 0.0625
  lightness: 0.1240977430716157
  saturation: 0.6875
  rhythmicContrast: 0.0017939356621354818
purpose: []
